version: '2'

services:
  web:
    image: lavoweb/php-5.6
    ports:
      - "80:80"
    volumes:
      - /media/rbrasier/DATA/Perso/www:/var/www/html
      - "./timezone.ini:/usr/local/etc/php/conf.d/timezone.ini"
    links:
      - db:db
  db:
    image: mysql:5.7
    volumes:
      - /media/rbrasier/DATA/Perso/data_docker/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
  myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8888:80"
    links:
      - db:db

# $ sudo dockerd
# $ docker-compose up