version: '2'

services:
  web:
    image: lavoweb/php-7.3
    ports:
      - "80:80"
    volumes:
      - ${path}/www:/var/www/html
      - ./timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
      - ./php.ini:/etc/php7/apache2/conf.d/php.ini
      - ./vhost.conf:/etc/apache2/sites-enabled/vhost-ssl.conf
      - ./hosts:/etc/hosts
    links:
      - db:db
  db:
    image: mysql:5.7
    volumes:
      - ${path}/data_docker/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
  myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8888:80"
    links:
      - db:db

# $ sudo dockerd
# $ docker-compose up
